---
# handlers file for cicd

# Reload Systemd Configs
- name: reload systemd
  systemd:
    daemon_reload: yes

# Start service
- name: start service
  systemd:
    name: "{{ service_name }}"
    state: started
    enabled: yes

# Restart service
- name: restart service
  systemd:
    name: "{{ service_name }}"
    state: restarted

# Start firewalld
- name: start firewall
  systemd:
    name: firewalld
    state: started
    enabled: yes

# Restart firewalld
- name: restart firewall
  systemd:
    name: firewalld
    state: restarted

# Disable selinux
- name: set selinux
  selinux:
    policy: targeted
    state: permissive
