---
# tasks file for cicd

#   Firewall
- name: Firewall | Add specific variables
  include_vars: "firewall.yml"

- name: Firewall | Add Firewall tasks
  include_tasks: "firewall.yml"

#   Nexus
- name: Nexus | Add specific variables
  include_vars: "nexus.yml"
  when: nexus_install and inventory_hostname in nexus_server

- name: Nexus | Add Nexus tasks
  include_tasks: "nexus.yml"
  when: nexus_install and inventory_hostname in nexus_server
